Repository JiratchayaPhinyodom/Period-Pejai, pull requests merged in 2022-11, with the labels that each got.

#33 all components from iteration 3
  front-end/src/components/Calendar.js
  front-end/src/components/Dashboard.css
  front-end/src/components/Dashboard.js
  front-end/src/components/calendar.css
  front-end/src/components/component_setting/input/input.css
  front-end/src/components/component_setting/profile/profile.js
  front-end/src/components/component_setting/toggle/toggle_period.css
  front-end/src/components/home_styles.css
  front-end/src/components/pics/line_button.png
Labels: enhancement

#34 Notification feature adding
  front-end/package-lock.json
  front-end/package.json
  front-end/src/components/Calendar.js
  front-end/src/components/Dashboard.js
  front-end/src/components/Home.js
Labels: enhancement

#35 Edit on buttons, pop ups, and calendar
  front-end/package-lock.json
  front-end/package.json
  front-end/src/components/Calendar.js
  front-end/src/components/Dashboard.css
  front-end/src/components/Dashboard.js
  front-end/src/components/Home.js
  front-end/src/components/calendar.css
  front-end/src/components/component_setting/input/input.css
  front-end/src/components/component_setting/profile/profile.js
  front-end/src/components/component_setting/toggle/toggle_period.css
  front-end/src/components/home_styles.css
  front-end/src/components/pics/line_button.png
Labels: enhancement

#38 Login system using google account
  front-end/src/components/Login.js
  front-end/src/firebase.js
Labels: enhancement

#39 Fix bugs on home page
  front-end/src/components/Calendar.js
  front-end/src/components/Dashboard.js
  front-end/src/components/Home.js
  front-end/src/components/Login.js
  front-end/src/firebase.js
Labels: bug, enhancement

#63 Connect frameworks
  front-end/package-lock.json
  front-end/package.json
  front-end/src/components/App.js
  front-end/src/components/Calendar.js
  front-end/src/components/Dashboard.css
  front-end/src/components/Dashboard.js
  front-end/src/components/ForgotPassword.js
  front-end/src/components/Home.js
  front-end/src/components/Login.css
  front-end/src/components/Login.js
  front-end/src/components/PrivateRoute.js
  front-end/src/components/PrivateRouter.js
  front-end/src/components/Router.js
  front-end/src/components/Setting.js
  front-end/src/components/Signup.js
  front-end/src/components/UpdateProfile.js
  front-end/src/components/calendar.css
  front-end/src/components/home_styles.css
  front-end/src/components/pics/droplet.png
  front-end/src/contexts/AuthContext.js
  period/api_period/forms.py
  period/api_period/migrations/0001_initial.py
  period/api_period/migrations/0002_delete_todo.py
  period/api_period/migrations/0003_initial.py
  period/api_period/migrations/0004_setting.py
  period/api_period/models.py
  period/api_period/serializers.py
  period/api_period/tests.py
  period/api_period/urls.py
  period/api_period/views.py
  period/db.sqlite3
  period/period/settings.py
Labels: enhancement

#66 Connect Frameworks new
  front-end/package-lock.json
  front-end/package.json
  front-end/src/components/Calendar.js
  front-end/src/components/Dashboard.css
  front-end/src/components/Dashboard.js
  front-end/src/components/Home.js
  front-end/src/components/calendar.css
  front-end/src/components/home_styles.css
  front-end/src/components/pics/droplet.png
  period/api_period/forms.py
  period/api_period/migrations/0001_initial.py
  period/api_period/migrations/0002_delete_todo.py
  period/api_period/migrations/0003_initial.py
  period/api_period/migrations/0004_setting.py
  period/api_period/models.py
  period/api_period/serializers.py
  period/api_period/urls.py
  period/api_period/views.py
  period/db.sqlite3
Labels: enhancement

#67 Pull request for demo deploy in master
  front-end/src/components/App.js
  front-end/src/components/Calendar.js
  front-end/src/components/Dashboard.css
  front-end/src/components/Dashboard.js
  front-end/src/components/ForgotPassword.js
  front-end/src/components/Home.js
  front-end/src/components/Login.css
  front-end/src/components/Login.js
  front-end/src/components/PrivateRoute.js
  front-end/src/components/Router.js
  front-end/src/components/Signup.js
  front-end/src/components/UpdateProfile.js
  front-end/src/components/calendar.css
  front-end/src/components/home_styles.css
  front-end/src/components/pics/droplet.png
  front-end/src/contexts/AuthContext.js
  period/api_period/admin.py
  period/api_period/apps.py
  period/api_period/crons.py
  period/api_period/forms.py
  period/api_period/line_notify.py
  period/api_period/migrations/0001_initial.py
  period/api_period/migrations/0002_delete_todo.py
  period/api_period/migrations/0003_initial.py
  period/api_period/migrations/0004_setting.py
  period/api_period/models.py
  period/api_period/serializers.py
  period/api_period/tests.py
  period/api_period/tests/__init__.py
  period/api_period/tests/tests_data_setting_page.py
  period/api_period/tests/tests_home_page.py
  period/api_period/tests/tests_model.py
  period/api_period/urls.py
  period/api_period/views.py
  period/db.sqlite3
  period/period/settings.py
Labels: enhancement

#95 Add e2e test #94
  e2e.py
Labels: documentation, enhancement
